- name: git (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Download git-completion.bash
      get_url:
        url:  https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
        dest: ~/.git-completion.bash

    - name: Add bash completion for git
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: git-completion.bash"
        block: |
          if [ -f ~/.git-completion.bash ]; then
            . ~/.git-completion.bash
          fi

    - name: Add default user in .gitconfig
      blockinfile:
        path: ~/.gitconfig
        marker: "### {mark} Ansible managed: .gitconfig"
        block: | 
          [user]
            email = christian@faxity.se
            name = Christian Norrman
          [init]
            defaultBranch = main
