- name: git (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code extensions
      command: ../vscode/invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - bierner.markdown-preview-github-styles
        - eamodio.gitlens
        - github.remotehub
        - cschleiden.vscode-github-actions
        - codezombiech.gitignore
