- name: .NET (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install global tools
      command: dotnet tool install -g {{ item }}
      args:
        creates: ~/.dotnet/tools/.store/{{ item }}
      loop:
        - coverlet.console
        - dotnet-depends
        - dotnet-format
        - dotnet-outdated-tool
        - dotnet-reportgenerator-globaltool
        - dotnet-retire
        - dotnet-ef

    - name: Install templates
      command: dotnet new -install {{ item }}
      loop:
        - Umbraco.Templates

    - name: Create Omnisharp config file
      copy:
        src: omnisharp.json
        dest: ~/.omnisharp/omnisharp.json


