- name: .NET (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install VS Code extensions
      command: ../vscode/invoke-code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - formulahendry.dotnet-test-explorer              # .NET Core Test Explorer
        - k--kato.docomment                               # C# XML Documentation Comments
        - ms-dotnettools.csharp                           # Dotnet support
        - gaoshan0621.csharp-format-usings                # Dotnet usings formatter
        - fernandoescolar.vscode-solution-explorer        # Dotnet solution explorer
        - jmrog.vscode-nuget-package-manager              # NuGet Package Manager
