- name: NodeJS
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Node Version Manager
      shell:
        cmd: "curl -L https://bit.ly/n-install | bash"
        warn: false
      args:
        creates: ~/.nvm/install.sh
