- name: NodeJS (customization)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Test for installed NodeJS LTS
      shell: bash -ic "n which lts" >/dev/null
      register: n_which
      ignore_errors: yes

    - name: Install NodeJS LTS
      command: bash -ic "n lts"
      when: n_which.failed

    - name: Use NodeJS LTS by default
      command: bash -ic "n lts"
      when: n_which.failed
